name: Bug report
description: Report a reproducible defect
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What is broken?
      placeholder: A clear and concise description of the bug
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Reproduction steps
      description: Exact steps to reproduce
      placeholder: |
        1. Run ...
        2. Press ...
        3. Observe ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: OS, compiler, build preset, and version/tag
      placeholder: macOS 15, AppleClang 17, vcpkg-debug, v0.1.0
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / screenshots (optional)
