name: Feature request
description: Suggest an enhancement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem are you trying to solve?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: What would you like to happen?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any alternative approaches?

  - type: textarea
    id: scope
    attributes:
      label: Scope and impact
      description: Affected modules (`core`, `app`, build, docs, CI, etc.)
    validations:
      required: true
